from __future__ import annotations

from mcp.types import Tool

HELP_MAP: dict[str, str] = {
    "tool_help": "tool_help(name?) -> 查看工具说明。name 为空则返回全部工具。",
    "note_add": "note_add(name, body?) -> 新增笔记，返回 note id。",
    "note_get": "note_get(id) -> 查看单条笔记详情。",
    "note_update": "note_update(id, name?, body?) -> 更新笔记，至少传 name/body 之一。",
    "note_list": "note_list(limit=20, offset=0) -> 分页列出笔记。",
    "note_search": "note_search(query, limit=20, offset=0) -> 关键词搜索笔记。",
    "note_delete": "note_delete(id) -> 删除指定笔记。",
    "task_add": "task_add(name, description?, priority?, due_date?) -> 新增任务。",
    "task_list": "task_list(status='all', priority='all', limit=20, offset=0) -> 分页筛选任务。",
    "task_update": "task_update(id, name?, description?, status?, priority?, due_date?) -> 更新任务。",
    "task_done": "task_done(id) -> 快速标记任务为 done。",
    "task_delete": "task_delete(id) -> 删除任务。",
    "task_stats": "task_stats() -> 输出 total/todo/doing/done 统计。",
    "add/project": "add/project(id, name, describe?, location?, environment?, languages?, libraries?, status='active', owner?) -> 新增项目。",
    "update/project": "update/project(id, name?, describe?, location?, environment?, languages?, libraries?, status?, owner?) -> 更新项目。",
    "list/project": "list/project(status='all', limit=20, offset=0) -> 列出项目。",
    "get/project": "get/project(id) -> 获取项目详情。",
    "delete/project": "delete/project(id) -> 删除项目。",
    "add/progress": "add/progress(project_id, name, feature?, context?, status?, priority?, progress?, milestone?) -> 新增进度项。",
    "update/progress": "update/progress(project_id, task_id, name?, feature?, context?, status?, priority?, progress?, milestone?) -> 更新进度项。",
    "list/progress": "list/progress(project_id, status='all', limit=20, offset=0) -> 列出进度项。",
    "stats/progress": "stats/progress(project_id) -> 输出项目进度统计。",
    "add/todo": "add/todo(project_id, name, feature?, context?, step_order?, status?) -> 为项目新增执行步骤。",
    "update/todo": "update/todo(project_id, id, name?, feature?, context?, step_order?, status?) -> 更新执行步骤。",
    "done/todo": "done/todo(project_id, id) -> 将执行步骤标记为 done。",
    "list/todo": "list/todo(project_id, status='all', limit=20, offset=0) -> 列出项目执行步骤。",
    "delete/todo": "delete/todo(project_id, id) -> 删除项目执行步骤。",
    "add/docs": "add/docs(name, content?, tags?, project_id?) -> 新增知识文档；project_id 为空写入公共知识。",
    "get/docs": "get/docs(id) -> 获取知识文档详情。",
    "list/docs": "list/docs(scope='all', project_id?, query?, limit=20, offset=0) -> 列出知识文档。",
    "search/docs": "search/docs(query, scope='all', project_id?, limit=20, offset=0) -> 搜索知识文档。",
    "update/docs": "update/docs(id, name?, content?, tags?, project_id?) -> 更新知识文档；project_id 传空可转为公共知识。",
    "delete/docs": "delete/docs(id) -> 删除知识文档。",
    "add/dict": "add/dict(name, value?, tags?, project_id?) -> 新增词典项；project_id 为空写入公共词典。",
    "get/dict": "get/dict(id) -> 获取词典项详情。",
    "get/dict/by-name": "get/dict/by-name(name, scope='auto', project_id?) -> 按名称获取词典项。",
    "list/dict": "list/dict(scope='all', project_id?, query?, limit=20, offset=0) -> 列出词典项。",
    "update/dict": "update/dict(id, name?, value?, tags?, project_id?) -> 更新词典项。",
    "delete/dict": "delete/dict(id) -> 删除词典项。",
    "add/prompt": "add/prompt(name, content?, tags?, project_id?) -> 新增提示词模板。",
    "get/prompt": "get/prompt(id) -> 获取提示词模板详情。",
    "get/prompt/by-name": "get/prompt/by-name(name, scope='auto', project_id?) -> 按名称获取提示词模板。",
    "list/prompt": "list/prompt(scope='all', project_id?, query?, limit=20, offset=0) -> 列出提示词模板。",
    "update/prompt": "update/prompt(id, name?, content?, tags?, project_id?) -> 更新提示词模板。",
    "render/prompt": "render/prompt(id, variables?, mode='loose') -> 渲染提示词模板。",
    "delete/prompt": "delete/prompt(id) -> 删除提示词模板。",
    "add/memory": "add/memory(project_id, key, value, scope='project', namespace='default', ttl_seconds?) -> 写入记忆。",
    "get/memory": "get/memory(project_id, key, scope='project', namespace='default') -> 获取单条记忆。",
    "list/memory": "list/memory(project_id, scope='all', namespace?, limit=20, offset=0) -> 列出记忆。",
    "update/memory": "update/memory(project_id, key, value, scope='project', namespace='default', ttl_seconds?) -> 更新记忆。",
    "delete/memory": "delete/memory(project_id, key, scope='project', namespace='default') -> 删除记忆。",
    "clear/memory": "clear/memory(project_id, scope='session') -> 清理某 scope 的记忆。",
    "add/snippet": "add/snippet(name, language?, content?, tags?, project_id?) -> 新增代码片段；project_id 为空写入公共片段库。",
    "get/snippet": "get/snippet(id) -> 获取片段详情。",
    "list/snippet": "list/snippet(scope='all', project_id?, language?, limit=20, offset=0) -> 列出代码片段。",
    "search/snippet": "search/snippet(query, limit=20, offset=0) -> 搜索代码片段。",
    "update/snippet": "update/snippet(id, name?, language?, content?, tags?) -> 更新代码片段。",
    "delete/snippet": "delete/snippet(id) -> 删除代码片段。",
    "set/env": "set/env(project_id, key, value?, description?) -> 写入/覆盖项目环境变量。",
    "get/env": "get/env(project_id, key) -> 获取单个项目环境变量。",
    "list/env": "list/env(project_id, limit=50, offset=0) -> 列出项目所有环境变量。",
    "delete/env": "delete/env(project_id, key) -> 删除项目环境变量。",
    "add/log": "add/log(summary, event_type='info', detail?, project_id?) -> 写入事件日志。",
    "get/log": "get/log(id) -> 获取日志详情。",
    "list/log": "list/log(project_id?, event_type?, limit=30, offset=0) -> 列出事件日志。",
    "clear/log": "clear/log(project_id?, event_type?) -> 清除日志（project_id/event_type 至少传一个）。",
    "query/hot-events": "query/hot-events(topic, date='today', timezone='Asia/Shanghai', region='global', scope='hot', limit=10, lang='zh-CN', strict_mode=true) -> 统一参数查询 topic 热点资讯。",
}

TOOL_ORDER: list[str] = [
    "tool_help",
    "note_add",
    "note_get",
    "note_update",
    "note_list",
    "note_search",
    "note_delete",
    "task_add",
    "task_list",
    "task_update",
    "task_done",
    "task_delete",
    "task_stats",
    "add/project",
    "update/project",
    "list/project",
    "get/project",
    "delete/project",
    "add/progress",
    "update/progress",
    "list/progress",
    "stats/progress",
    "add/todo",
    "update/todo",
    "done/todo",
    "list/todo",
    "delete/todo",
    "add/docs",
    "get/docs",
    "list/docs",
    "search/docs",
    "update/docs",
    "delete/docs",
    "add/dict",
    "get/dict",
    "get/dict/by-name",
    "list/dict",
    "update/dict",
    "delete/dict",
    "add/prompt",
    "get/prompt",
    "get/prompt/by-name",
    "list/prompt",
    "update/prompt",
    "render/prompt",
    "delete/prompt",
    "add/memory",
    "get/memory",
    "list/memory",
    "update/memory",
    "delete/memory",
    "clear/memory",
    "add/snippet",
    "get/snippet",
    "list/snippet",
    "search/snippet",
    "update/snippet",
    "delete/snippet",
    "set/env",
    "get/env",
    "list/env",
    "delete/env",
    "add/log",
    "get/log",
    "list/log",
    "clear/log",
    "query/hot-events",
]

ALLOWED_TOOLS: set[str] = set(TOOL_ORDER)


def _tool(
    *,
    name: str,
    description: str,
    x_tags: list[str],
    properties: dict,
    required: list[str] | None = None,
) -> Tool:
    schema = {
        "type": "object",
        "x-tags": x_tags,
        "properties": properties,
        "additionalProperties": False,
    }
    if required:
        schema["required"] = required
    return Tool(name=name, description=description, inputSchema=schema)


def build_tools() -> list[Tool]:
    return [
        _tool(
            name="tool_help",
            description="查看工具说明；不传 name 返回全部工具概览",
            x_tags=["system", "help"],
            properties={"name": {"type": "string", "enum": TOOL_ORDER}},
        ),
        _tool(
            name="note_add",
            description="新增一条笔记",
            x_tags=["note", "add", "create", "write"],
            properties={
                "name": {"type": "string", "minLength": 1},
                "body": {"type": "string"},
            },
            required=["name"],
        ),
        _tool(
            name="note_get",
            description="按 id 获取一条笔记详情",
            x_tags=["note", "get", "detail", "read"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="note_update",
            description="更新笔记名称和正文（至少提供一个字段）",
            x_tags=["note", "update", "edit", "modify"],
            properties={
                "id": {"type": "integer", "minimum": 1},
                "name": {"type": "string", "minLength": 1},
                "body": {"type": "string"},
            },
            required=["id"],
        ),
        _tool(
            name="note_list",
            description="列出最近笔记",
            x_tags=["note", "list", "browse", "paginate"],
            properties={
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
        ),
        _tool(
            name="note_search",
            description="按关键词搜索名称和正文",
            x_tags=["note", "search", "find", "query", "fulltext"],
            properties={
                "query": {"type": "string", "minLength": 1},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
            required=["query"],
        ),
        _tool(
            name="note_delete",
            description="删除指定 id 的笔记",
            x_tags=["note", "delete", "remove"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="task_add",
            description="新增任务",
            x_tags=["task", "add", "create", "todo"],
            properties={
                "name": {"type": "string", "minLength": 1},
                "description": {"type": "string"},
                "priority": {"type": "string", "enum": ["low", "medium", "high"]},
                "due_date": {"type": "string", "description": "截止日期，建议格式 YYYY-MM-DD"},
            },
            required=["name"],
        ),
        _tool(
            name="task_list",
            description="列出任务，可按状态和优先级过滤",
            x_tags=["task", "list", "browse", "filter"],
            properties={
                "status": {"type": "string", "enum": ["all", "todo", "doing", "done"]},
                "priority": {"type": "string", "enum": ["all", "low", "medium", "high"]},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
        ),
        _tool(
            name="task_update",
            description="更新任务（名称/描述/状态/优先级/截止日期）",
            x_tags=["task", "update", "edit", "modify"],
            properties={
                "id": {"type": "integer", "minimum": 1},
                "name": {"type": "string", "minLength": 1},
                "description": {"type": "string"},
                "status": {"type": "string", "enum": ["todo", "doing", "done"]},
                "priority": {"type": "string", "enum": ["low", "medium", "high"]},
                "due_date": {"type": ["string", "null"], "description": "传 null 可清空截止日期"},
            },
            required=["id"],
        ),
        _tool(
            name="task_done",
            description="将任务标记为 done",
            x_tags=["task", "done", "complete", "finish"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="task_delete",
            description="删除任务",
            x_tags=["task", "delete", "remove"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="task_stats",
            description="统计任务总数与各状态数量",
            x_tags=["task", "stats", "summary", "count"],
            properties={},
        ),
        _tool(
            name="add/project",
            description="新增项目",
            x_tags=["project", "add", "create"],
            properties={
                "id": {"type": "string", "minLength": 1},
                "name": {"type": "string", "minLength": 1},
                "describe": {"type": "string"},
                "location": {"type": "string"},
                "environment": {"type": "string"},
                "languages": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
                "libraries": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
                "status": {"type": "string", "enum": ["active", "paused", "archived"]},
                "owner": {"type": "string"},
            },
            required=["id", "name"],
        ),
        _tool(
            name="update/project",
            description="更新项目",
            x_tags=["project", "update", "edit"],
            properties={
                "id": {"type": "string", "minLength": 1},
                "name": {"type": "string", "minLength": 1},
                "describe": {"type": "string"},
                "location": {"type": "string"},
                "environment": {"type": "string"},
                "languages": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
                "libraries": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
                "status": {"type": "string", "enum": ["active", "paused", "archived"]},
                "owner": {"type": "string"},
            },
            required=["id"],
        ),
        _tool(
            name="list/project",
            description="列出项目",
            x_tags=["project", "list", "browse"],
            properties={
                "status": {"type": "string", "enum": ["all", "active", "paused", "archived"]},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
        ),
        _tool(
            name="get/project",
            description="获取项目详情",
            x_tags=["project", "get", "detail"],
            properties={"id": {"type": "string", "minLength": 1}},
            required=["id"],
        ),
        _tool(
            name="delete/project",
            description="删除项目",
            x_tags=["project", "delete", "remove"],
            properties={"id": {"type": "string", "minLength": 1}},
            required=["id"],
        ),
        _tool(
            name="add/progress",
            description="新增项目进度项",
            x_tags=["progress", "add", "create"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "name": {"type": "string", "minLength": 1},
                "feature": {"type": "string"},
                "context": {"type": "string"},
                "status": {"type": "string", "enum": ["todo", "doing", "done"]},
                "priority": {"type": "string", "enum": ["low", "medium", "high"]},
                "progress": {"type": "integer", "minimum": 0, "maximum": 100},
                "milestone": {"type": "string"},
            },
            required=["project_id", "name"],
        ),
        _tool(
            name="update/progress",
            description="更新项目进度项",
            x_tags=["progress", "update", "edit"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "task_id": {"type": "integer", "minimum": 1},
                "name": {"type": "string", "minLength": 1},
                "feature": {"type": "string"},
                "context": {"type": "string"},
                "status": {"type": "string", "enum": ["todo", "doing", "done"]},
                "priority": {"type": "string", "enum": ["low", "medium", "high"]},
                "progress": {"type": "integer", "minimum": 0, "maximum": 100},
                "milestone": {"type": "string"},
            },
            required=["project_id", "task_id"],
        ),
        _tool(
            name="list/progress",
            description="列出项目进度项",
            x_tags=["progress", "list", "browse"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "status": {"type": "string", "enum": ["all", "todo", "doing", "done"]},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
            required=["project_id"],
        ),
        _tool(
            name="stats/progress",
            description="统计项目进度项数量",
            x_tags=["progress", "stats", "summary"],
            properties={"project_id": {"type": "string", "minLength": 1}},
            required=["project_id"],
        ),
        _tool(
            name="add/todo",
            description="为项目新增执行步骤",
            x_tags=["todo", "add", "project"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "name": {"type": "string", "minLength": 1},
                "feature": {"type": "string"},
                "context": {"type": "string"},
                "step_order": {"type": "integer", "minimum": 1},
                "status": {"type": "string", "enum": ["todo", "doing", "done"]},
            },
            required=["project_id", "name"],
        ),
        _tool(
            name="update/todo",
            description="更新项目执行步骤",
            x_tags=["todo", "update", "project"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "id": {"type": "integer", "minimum": 1},
                "name": {"type": "string", "minLength": 1},
                "feature": {"type": "string"},
                "context": {"type": "string"},
                "step_order": {"type": "integer", "minimum": 1},
                "status": {"type": "string", "enum": ["todo", "doing", "done"]},
            },
            required=["project_id", "id"],
        ),
        _tool(
            name="done/todo",
            description="将项目执行步骤标记为完成",
            x_tags=["todo", "done", "project"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "id": {"type": "integer", "minimum": 1},
            },
            required=["project_id", "id"],
        ),
        _tool(
            name="list/todo",
            description="列出项目执行步骤",
            x_tags=["todo", "list", "project"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "status": {"type": "string", "enum": ["all", "todo", "doing", "done"]},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
            required=["project_id"],
        ),
        _tool(
            name="delete/todo",
            description="删除项目执行步骤",
            x_tags=["todo", "delete", "project"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "id": {"type": "integer", "minimum": 1},
            },
            required=["project_id", "id"],
        ),
        _tool(
            name="add/docs",
            description="新增知识文档（支持公共知识和项目知识）",
            x_tags=["docs", "add", "create", "knowledge"],
            properties={
                "name": {"type": "string", "minLength": 1},
                "content": {"type": "string"},
                "tags": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
                "project_id": {"type": "string", "minLength": 1},
            },
            required=["name"],
        ),
        _tool(
            name="get/docs",
            description="按 id 获取知识文档详情",
            x_tags=["docs", "get", "detail"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="list/docs",
            description="列出知识文档（支持公共与项目过滤）",
            x_tags=["docs", "list", "browse"],
            properties={
                "scope": {"type": "string", "enum": ["all", "public", "project"]},
                "project_id": {"type": "string", "minLength": 1},
                "query": {"type": "string", "minLength": 1},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
        ),
        _tool(
            name="search/docs",
            description="搜索知识文档（支持公共与项目过滤）",
            x_tags=["docs", "search", "find", "knowledge"],
            properties={
                "query": {"type": "string", "minLength": 1},
                "scope": {"type": "string", "enum": ["all", "public", "project"]},
                "project_id": {"type": "string", "minLength": 1},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
            required=["query"],
        ),
        _tool(
            name="update/docs",
            description="更新知识文档（可切换公共/项目绑定）",
            x_tags=["docs", "update", "edit"],
            properties={
                "id": {"type": "integer", "minimum": 1},
                "name": {"type": "string", "minLength": 1},
                "content": {"type": "string"},
                "tags": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
                "project_id": {
                    "anyOf": [
                        {"type": "string", "minLength": 1},
                        {"type": "null"},
                    ]
                },
            },
            required=["id"],
        ),
        _tool(
            name="delete/docs",
            description="删除知识文档",
            x_tags=["docs", "delete", "remove"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="add/dict",
            description="新增词典项（支持公共和项目绑定）",
            x_tags=["dict", "add", "create", "knowledge"],
            properties={
                "name": {"type": "string", "minLength": 1},
                "value": {"type": "string"},
                "tags": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
                "project_id": {"type": "string", "minLength": 1},
            },
            required=["name"],
        ),
        _tool(
            name="get/dict",
            description="按 id 获取词典项详情",
            x_tags=["dict", "get", "detail"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="get/dict/by-name",
            description="按名称获取词典项（支持 public/project/auto）",
            x_tags=["dict", "get", "name"],
            properties={
                "name": {"type": "string", "minLength": 1},
                "scope": {"type": "string", "enum": ["auto", "public", "project"]},
                "project_id": {"type": "string", "minLength": 1},
            },
            required=["name"],
        ),
        _tool(
            name="list/dict",
            description="列出词典项（支持公共与项目过滤）",
            x_tags=["dict", "list", "browse"],
            properties={
                "scope": {"type": "string", "enum": ["all", "public", "project"]},
                "project_id": {"type": "string", "minLength": 1},
                "query": {"type": "string", "minLength": 1},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
        ),
        _tool(
            name="update/dict",
            description="更新词典项（可切换公共/项目绑定）",
            x_tags=["dict", "update", "edit"],
            properties={
                "id": {"type": "integer", "minimum": 1},
                "name": {"type": "string", "minLength": 1},
                "value": {"type": "string"},
                "tags": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
                "project_id": {
                    "anyOf": [
                        {"type": "string", "minLength": 1},
                        {"type": "null"},
                    ]
                },
            },
            required=["id"],
        ),
        _tool(
            name="delete/dict",
            description="删除词典项",
            x_tags=["dict", "delete", "remove"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="add/prompt",
            description="新增提示词模板（支持公共和项目绑定）",
            x_tags=["prompt", "add", "create", "template"],
            properties={
                "name": {"type": "string", "minLength": 1},
                "content": {"type": "string"},
                "tags": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
                "project_id": {"type": "string", "minLength": 1},
            },
            required=["name"],
        ),
        _tool(
            name="get/prompt",
            description="按 id 获取提示词模板详情",
            x_tags=["prompt", "get", "detail"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="get/prompt/by-name",
            description="按名称获取提示词模板（支持 public/project/auto）",
            x_tags=["prompt", "get", "name"],
            properties={
                "name": {"type": "string", "minLength": 1},
                "scope": {"type": "string", "enum": ["auto", "public", "project"]},
                "project_id": {"type": "string", "minLength": 1},
            },
            required=["name"],
        ),
        _tool(
            name="list/prompt",
            description="列出提示词模板（支持公共与项目过滤）",
            x_tags=["prompt", "list", "browse"],
            properties={
                "scope": {"type": "string", "enum": ["all", "public", "project"]},
                "project_id": {"type": "string", "minLength": 1},
                "query": {"type": "string", "minLength": 1},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
        ),
        _tool(
            name="update/prompt",
            description="更新提示词模板（可切换公共/项目绑定）",
            x_tags=["prompt", "update", "edit"],
            properties={
                "id": {"type": "integer", "minimum": 1},
                "name": {"type": "string", "minLength": 1},
                "content": {"type": "string"},
                "tags": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
                "project_id": {
                    "anyOf": [
                        {"type": "string", "minLength": 1},
                        {"type": "null"},
                    ]
                },
            },
            required=["id"],
        ),
        _tool(
            name="render/prompt",
            description="按变量渲染提示词模板（strict/loose）",
            x_tags=["prompt", "render", "template"],
            properties={
                "id": {"type": "integer", "minimum": 1},
                "variables": {"type": "object"},
                "mode": {"type": "string", "enum": ["strict", "loose"]},
            },
            required=["id"],
        ),
        _tool(
            name="delete/prompt",
            description="删除提示词模板",
            x_tags=["prompt", "delete", "remove"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="add/memory",
            description="新增项目记忆",
            x_tags=["memory", "add", "create"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "scope": {"type": "string", "enum": ["session", "project", "global"]},
                "namespace": {"type": "string"},
                "key": {"type": "string", "minLength": 1},
                "value": {"type": "string"},
                "ttl_seconds": {"type": "integer", "minimum": 1},
            },
            required=["project_id", "key", "value"],
        ),
        _tool(
            name="get/memory",
            description="获取单条项目记忆",
            x_tags=["memory", "get", "detail"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "scope": {"type": "string", "enum": ["session", "project", "global"]},
                "namespace": {"type": "string"},
                "key": {"type": "string", "minLength": 1},
            },
            required=["project_id", "key"],
        ),
        _tool(
            name="list/memory",
            description="列出项目记忆",
            x_tags=["memory", "list", "browse"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "scope": {"type": "string", "enum": ["all", "session", "project", "global"]},
                "namespace": {"type": "string"},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
            required=["project_id"],
        ),
        _tool(
            name="update/memory",
            description="更新项目记忆",
            x_tags=["memory", "update", "edit"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "scope": {"type": "string", "enum": ["session", "project", "global"]},
                "namespace": {"type": "string"},
                "key": {"type": "string", "minLength": 1},
                "value": {"type": "string"},
                "ttl_seconds": {"type": "integer", "minimum": 1},
            },
            required=["project_id", "key", "value"],
        ),
        _tool(
            name="delete/memory",
            description="删除项目记忆",
            x_tags=["memory", "delete", "remove"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "scope": {"type": "string", "enum": ["session", "project", "global"]},
                "namespace": {"type": "string"},
                "key": {"type": "string", "minLength": 1},
            },
            required=["project_id", "key"],
        ),
        _tool(
            name="clear/memory",
            description="清理某个 scope 的项目记忆",
            x_tags=["memory", "clear", "cleanup"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "scope": {"type": "string", "enum": ["session", "project", "global"]},
            },
            required=["project_id"],
        ),
        _tool(
            name="add/snippet",
            description="新增代码/文本片段（支持公共和项目绑定）",
            x_tags=["snippet", "add", "create", "code"],
            properties={
                "name": {"type": "string", "minLength": 1},
                "language": {"type": "string"},
                "content": {"type": "string"},
                "tags": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
                "project_id": {"type": "string", "minLength": 1},
            },
            required=["name"],
        ),
        _tool(
            name="get/snippet",
            description="按 id 获取片段详情",
            x_tags=["snippet", "get", "detail"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="list/snippet",
            description="列出代码/文本片段（可按 scope/language 过滤）",
            x_tags=["snippet", "list", "browse"],
            properties={
                "scope": {"type": "string", "enum": ["all", "public", "project"]},
                "project_id": {"type": "string", "minLength": 1},
                "language": {"type": "string"},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
        ),
        _tool(
            name="search/snippet",
            description="搜索代码/文本片段",
            x_tags=["snippet", "search", "find"],
            properties={
                "query": {"type": "string", "minLength": 1},
                "limit": {"type": "integer", "minimum": 1, "maximum": 100},
                "offset": {"type": "integer", "minimum": 0},
            },
            required=["query"],
        ),
        _tool(
            name="update/snippet",
            description="更新代码/文本片段",
            x_tags=["snippet", "update", "edit"],
            properties={
                "id": {"type": "integer", "minimum": 1},
                "name": {"type": "string", "minLength": 1},
                "language": {"type": "string"},
                "content": {"type": "string"},
                "tags": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "array", "items": {"type": "string"}},
                    ]
                },
            },
            required=["id"],
        ),
        _tool(
            name="delete/snippet",
            description="删除代码/文本片段",
            x_tags=["snippet", "delete", "remove"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="set/env",
            description="写入/覆盖项目环境变量（同 key 自动覆盖）",
            x_tags=["env", "set", "config", "project"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "key": {"type": "string", "minLength": 1},
                "value": {"type": "string"},
                "description": {"type": "string"},
            },
            required=["project_id", "key"],
        ),
        _tool(
            name="get/env",
            description="获取单个项目环境变量",
            x_tags=["env", "get", "config"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "key": {"type": "string", "minLength": 1},
            },
            required=["project_id", "key"],
        ),
        _tool(
            name="list/env",
            description="列出项目所有环境变量",
            x_tags=["env", "list", "config"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "limit": {"type": "integer", "minimum": 1, "maximum": 200},
                "offset": {"type": "integer", "minimum": 0},
            },
            required=["project_id"],
        ),
        _tool(
            name="delete/env",
            description="删除项目环境变量",
            x_tags=["env", "delete", "config"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "key": {"type": "string", "minLength": 1},
            },
            required=["project_id", "key"],
        ),
        _tool(
            name="add/log",
            description="写入事件/活动日志（可绑定项目）",
            x_tags=["log", "add", "event", "record"],
            properties={
                "summary": {"type": "string", "minLength": 1},
                "event_type": {"type": "string"},
                "detail": {"type": "string"},
                "project_id": {"type": "string", "minLength": 1},
            },
            required=["summary"],
        ),
        _tool(
            name="get/log",
            description="按 id 获取日志详情",
            x_tags=["log", "get", "detail"],
            properties={"id": {"type": "integer", "minimum": 1}},
            required=["id"],
        ),
        _tool(
            name="list/log",
            description="列出事件日志（可按 project_id/event_type 过滤）",
            x_tags=["log", "list", "browse", "event"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "event_type": {"type": "string"},
                "limit": {"type": "integer", "minimum": 1, "maximum": 200},
                "offset": {"type": "integer", "minimum": 0},
            },
        ),
        _tool(
            name="clear/log",
            description="清除事件日志（project_id/event_type 至少传一个）",
            x_tags=["log", "clear", "delete"],
            properties={
                "project_id": {"type": "string", "minLength": 1},
                "event_type": {"type": "string"},
            },
        ),
        _tool(
            name="query/hot-events",
            description="统一参数查询热点资讯（按 topic 聚合）",
            x_tags=["query", "hot", "events", "news"],
            properties={
                "topic": {"type": "string", "minLength": 1},
                "date": {"type": "string", "description": "today 或 YYYY-MM-DD"},
                "timezone": {"type": "string", "default": "Asia/Shanghai"},
                "region": {"type": "string", "default": "global"},
                "scope": {"type": "string", "enum": ["hot", "all"], "default": "hot"},
                "limit": {"type": "integer", "minimum": 1, "maximum": 50, "default": 10},
                "lang": {"type": "string", "default": "zh-CN"},
                "strict_mode": {"type": "boolean", "default": True},
            },
        ),
    ]
